### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by lakshyarao22** [AlfarexGuy2019/keyfox#2]
can't see text in tab bar

**Comment by nmathira** [comment]
facing the same issue,
![Screenshot_20211120_185646](https://user-images.githubusercontent.com/56417211/142747642-660fdb7a-2f20-4962-9ee6-755a585932f6.png)

Here is an image to illustrate the issue

**Comment by mrbooshehri** [comment]
Add the following lines somewhere in your ```userChrome.css``` 

```css
.tabbrowser-tab .tab-label  { color: var(--uc-inverted-colour) !important; }
.tab-close-button { fill: var(--uc-inverted-colour) !important }
```
